# Generated by Django 3.1.4 on 2021-01-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_main', '0008_auto_20210107_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AddField(
            model_name='comment',
            name='no',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
