# Generated by Django 3.1.4 on 2021-01-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_main', '0009_auto_20210107_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
