# Generated by Django 3.1.4 on 2021-01-03 19:07

from django.db import migrations, models
import rest_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=models.SET(rest_main.models.get_sentinel_user), to='rest_main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=models.SET(rest_main.models.get_sentinel_user), to='rest_main.profile')),
            ],
        ),
    ]
