# Generated by Django 3.1.4 on 2021-01-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_main', '0003_auto_20210104_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='rest_main.Comment'),
        ),
    ]
