# Generated by Django 3.1.4 on 2021-01-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_main', '0004_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
