# Generated by Django 3.1.4 on 2021-01-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_main', '0005_auto_20210107_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ManyToManyField(to='rest_main.Post'),
        ),
    ]
