# Generated by Django 3.1.4 on 2021-01-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_main', '0008_auto_20210107_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
